const actionTypes = {
    ADD_TODO: 'ADD_TODO',
    ADD_TODO_SUCCESS: 'ADD_TODO_SUCCESS',
    TOGGLE_TODO: 'TOGGLE_TODO',
    TOGGLE_TODO_SUCCESS: 'TOGGLE_TODO_SUCCESS',
    REQUEST_TODOS: 'FETCH_TODOS_REQUEST',
    RECEIVE_TODOS: 'FETCH_TODOS_SUCCESS',
    RECEIVE_TODOS_FAIL: 'FETCH_TODOS_FAILURE',
    SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER'
};

export default actionTypes;